config/routes.rb
LeapWeb::Application.routes.draw do
  #
  # Please do not use root_path or root_url. Use home_path and home_url instead,
  # so that the path will be correctly prefixed with the locale.
  #
  root :to => "home#index"
  get '(:locale)' => 'home#index', :locale => CommonLanguages.match_available, :as => 'home'

  #
  # HTTP Error Handling
  # instead of the default error pages use the errors controller and views
  #
  match '/404' => 'errors#not_found', via: [:get, :post]
  match '/500' => 'errors#server_error', via: [:get, :post]

  scope "(:locale)", :locale => CommonLanguages.match_available, :controller => 'pages', :action => 'show' do
    get 'privacy-policy', :as => 'privacy_policy'
    get 'terms-of-service', :as => 'terms_of_service'
    get 'about', :as => 'about'
    get 'contact', :as => 'contact'
    get 'pricing', :as => 'pricing'
    get 'bye', :as => 'bye'
  end

  get '/provider.json' => 'static_config#provider'

  namespace "api", { module: "api",
      path: "/:version/",
      defaults: {version: '2', format: 'json'},
      :constraints => { :id => /[^\/]+(?=\.json\z)|[^\/]+/, :version => /[12]/ }
      } do
    resources :sessions, :only => [:new, :create, :update]
    delete "logout" => "sessions#destroy", :as => "logout"
    resources :users, :only => [:create, :update, :destroy, :index, :show]
    resources :messages, :only => [:index, :update]
    resource :cert, :only => [:show, :create]
    resource :smtp_cert, :only => [:create]
    resource :service, :only => [:show]
    resources :configs, :only => [:index, :show]
    resources :identities, :only => [:show]
  end

  scope "(:locale)", :locale => CommonLanguages.match_available do
    get "login" => "sessions#new", :as => "login"
    delete "logout" => "sessions#destroy", :as => "logout"

    get "signup" => "account#new", :as => "signup"
    resources :users, :except => [:new, :create, :update] do
      # resource :email_settings, :only => [:edit, :update]
      # resources :email_aliases, :only => [:destroy], :id => /.*/
      post 'deactivate', on: :member
      post 'enable', on: :member
    end

    resources :invite_codes, :only => [:index, :destroy, :create]
    resources :identities, :only => [:index, :destroy]
  end

  get "/.well-known/host-meta" => 'webfinger#host_meta'
  get "/webfinger" => 'webfinger#search'
  get "/key/:login" => 'keys#show', :constraints => { :login => /[^\/]+/ }

end

app/models/user.rb
require 'login_format_validation'
require 'local_email'
require 'temporary_user'

class User < CouchRest::Model::Base
  include LoginFormatValidation

  property :login, String, :accessible => true
  property :password_verifier, String, :accessible => true
  property :password_salt, String, :accessible => true
  property :contact_email, String, :accessible => true
  property :contact_email_key, String, :accessible => true
  property :invite_code, String, :accessible => true
  property :braintree_customer_id, Integer, :accessible => true
  property :subscription_id, String, :accessible => true

  property :enabled, TrueClass, :default => true

  # these will be null by default but we shouldn't ever pull them directly, but only via the methods that will return the full ServiceLevel
  property :desired_service_level_code, Integer, :accessible => true
  property :effective_service_level_code, Integer, :accessible => true

  property :one_month_warning_sent, TrueClass

  before_save :update_effective_service_level

  validates :login, :password_salt, :password_verifier,
    :presence => true

  validates :login,
    :uniqueness => true,
    :if => :serverside?

  validate :identity_is_valid

  validates :password_salt, :password_verifier,
    :format => { :with => /\A[\dA-Fa-f]+\z/, :message => "Only hex numbers allowed" }

  validates :password, :presence => true,
    :confirmation => true,
    :format => { :with => /.{8}.*/, :message => "needs to be at least 8 characters long" }

  validates :contact_email, :allow_blank => true,
    :email => true,
    :mx_with_fallback => true


  validates_with InviteCodeValidator, :on => :create, :if => :invite_required?

  timestamps!

  design do
    own_path = Pathname.new(File.dirname(__FILE__))
    load_views(own_path.join('..', 'designs', 'user'))
    view :by_login
    view :by_created_at
  end # end of design

  include TemporaryUser # MUST come after designs are defined.

  def initialize(*args)
    super
    @invite_required = APP_CONFIG[:invite_required]
  end

  def self.login_starts_with(query)
    self.by_login.startkey(query).endkey(query + "\ufff0")
  end

  def reload
    @identity = nil
    super
  end

  def to_json(options={})
    to_hash.to_json(options)
  end

  def to_hash()
    {
      :login => self.login,
      :ok => self.valid?,
      :id => self.id,
      :enabled => self.enabled?,
    }
  end

  def salt
    password_salt.hex
  end

  def verifier
    password_verifier.hex
  end

  def username
    login
  end

  # use this if you want to get a working email address only.
  def email
    if effective_service_level.provides?('email')
      email_address
    end
  end

  # use this if you want the email address associated with a
  # user no matter if the user actually has a local email account
  def email_address
    LocalEmail.new(login)
  end

  # Since we are storing admins by login, we cannot allow admins to change their login.
  def is_admin?
    APP_CONFIG['admins'].include? self.login
  end

  def is_anonymous?
    false
  end

  def is_monitor?
    false
  end

  def invite_required?
    @invite_required
  end

  # should only be called for testing or monitoring purposes
  def ignore_invites!
    @invite_required = false
  end

  def most_recent_tickets(count=3)
    Ticket.for_user(self).limit(count).all #defaults to having most recent updated first
  end

  def messages
    #TODO for now this only shows unseen messages. Will we ever want seen ones? Is it necessary to store?
    Message.by_user_ids_to_show.key(self.id)
  end

  # DEPRECATED
  #
  # Please set the key on the identity directly
  # WARNING: This will not be serialized with the user record!
  # It is only a workaround for the key form.
  def public_key=(value)
    identity.set_key(:pgp, value)
  end

  # DEPRECATED
  #
  # Please access identity.keys[:pgp] directly
  def public_key
    identity.keys[:pgp]
  end

  def account
    Account.new(self)
  end

  # deprecated
  def identity
    @identity ||= Identity.for(self)
  end

  # deprecated
  def refresh_identity
    @identity = Identity.for(self)
  end

  def identities
    Identity.by_user_id.key(self.id)
  end

  def destroy_identities
    identities.each do |id|
      id.destroy
    end
  end


  def desired_service_level
    code = self.desired_service_level_code || APP_CONFIG[:default_service_level]
    ServiceLevel.new({id: code})
  end

  def effective_service_level
    code = self.effective_service_level_code || self.desired_service_level.id
    ServiceLevel.new({id: code})
  end

  def self.send_one_month_warnings

    # To determine warnings to send, need to get all users where one_month_warning_sent is not set, and where it was created greater than or equal to 1 month ago.
    # TODO: might want to further limit to enabled accounts, and, based on provider's service level configuration, for particular service levels.
    users_to_warn = User.by_created_at_and_one_month_warning_not_sent.endkey(Time.now-1.month)

    users_to_warn.each do |user|
      # instead of loop could use something like:
      # message.user_ids_to_show = users_to_warn.map(&:id)
      # but would still need to loop through users to store one_month_warning_sent

      if !@message
        # create a message for today's date
        # only want to create once, and only if it will be used.
        @message = Message.new(:text => I18n.t(:payment_one_month_warning, :date_in_one_month => (Time.now+1.month).strftime("%Y-%d-%m")))
      end

      @message.user_ids_to_show << user.id
      user.one_month_warning_sent = true
      user.save
    end
    @message.save if @message

  end

  def has_payment_info?
    braintree_customer_id
  end

  protected

  ##
  #  Validation Functions
  ##

  def identity_is_valid
    return if identity.valid?
    identity.errors.each do |attribute, error|
      errors.add(:login, error) unless errors[:login].include? error
    end
  end

  def password
    password_verifier
  end

  # used as a condition for validations that are server side only
  def serverside?
    true
  end

  def update_effective_service_level
    # TODO: Is this always the case? Might there be a situation where the admin has set the effective service level and we don't want it changed to match the desired one?
    if self.desired_service_level_code_changed?
      self.effective_service_level_code = self.desired_service_level_code
    end
  end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController
    include ControllerExtension::FetchUser

    # allow optional access to this controller using API auth tokens:
    before_filter :token_authenticate

    before_filter :fetch_user, :only => [:update, :destroy]
    before_filter :require_monitor, :only => [:index, :show]
    before_filter :require_login, :only => [:index, :update, :destroy]

    respond_to :json

    # used for autocomplete for admins in the web ui
    def index
      if params[:query]
        @users = User.login_starts_with(params[:query])
        respond_with @users.map(&:login).sort
      else
        render :json => {'error' => 'query required', 'status' => :unprocessable_entity}
      end
    end

    def show
      if params[:login]
        @user = User.find_by_login(params[:login])
      elsif params[:id]
        @user = User.find(params[:id])
      end
      if @user
        respond_with user_response
      else
        not_found
      end
    end

    def user_response
      @user.to_hash.tap do |user_hash|
        if @user == current_user
          user_hash['is_admin'] = @user.is_admin?
        end
      end
    end

    def create
      if current_user.is_monitor?
        create_test_account
      elsif APP_CONFIG[:allow_registration]
        create_account
      else
        head :forbidden
      end
    end

    def update
      @user.account.update params[:user]
      respond_with @user
    end

    def destroy
      @user.account.destroy(release_handles)
      if @user == current_user
        logout
      end
      render :json => {'success' => 'user deleted'}
    end

    private

    def release_handles
      current_user.is_monitor? || params[:identities] == "destroy"
    end

    # tester auth can only create test users.
    def create_test_account
      if User::is_test?(params[:user][:login])
        @user = Account.create(params[:user], :invite_required => false)
        respond_with @user
      else
        head :forbidden
      end
    end

    def create_account
      if APP_CONFIG[:allow_registration]
        @user = Account.create(params[:user])
        respond_with @user # return ID instead?
      else
        head :forbidden
      end
    end

  end
end

app/controllers/users_controller.rb
#
# This is an HTML-only controller. For the JSON-only controller, see v1/users_controller.rb
#

class UsersController < ApplicationController
  include ControllerExtension::FetchUser

  before_filter :require_login
  before_filter :require_admin, :only => [:index, :deactivate, :enable]
  before_filter :fetch_user, :except => [:index]

  respond_to :html

  def index
    if params[:query].present?
      if @user = User.find_by_login(params[:query])
        redirect_to @user
        return
      else
        @users = User.login_starts_with(params[:query])
      end
    else
      @users = User.by_created_at.descending
    end
    @users = @users.limit(100)
  end

  def show
  end

  def edit
  end

  def deactivate
    @user.account.disable
    flash[:notice] = I18n.t("actions.user_disabled_message", username: @user.username)
    redirect_to :back
  end

  def enable
    @user.account.enable
    flash[:notice] = I18n.t("actions.user_enabled_message", username: @user.username)
    redirect_to :back
  end

  def destroy
    @user.account.destroy
    flash[:notice] = I18n.t(:account_destroyed)
    # admins can destroy other users
    if @user != current_user
      redirect_to users_url
    else
      # let's remove the invalid session
      logout
      redirect_to bye_url
    end
  end

  protected

  def user_params
    if admin?
      params.require(:user).permit(:effective_service_level)
    else
      params.require(:user).permit(:password, :password_confirmation)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_form_class(*classes)
    (classes + ['user', 'hidden', 'js-show', (@user.new_record? ? 'new' : 'edit')]).compact.join(' ')
  end

  def wrapped(item, options = {})
    options[:as] ||= :div
    content_tag options[:as], :class => dom_class(item), :id => dom_id(item) do
      yield
    end
  end

end

app/views/users/_change_password.html.haml
-#
-# CHANGE PASSWORD
-#
-# * everything about this form is handled with javascript. So take care when changing any ids.
-# * the login is required when changing the password because it is used as part of the salt when calculating the password verifier.
-#   however, we don't want the user to change their login without generating a new key, so we hide the ui for this
-#   (although it works perfectly fine to change username if the field was visible).
-#

- form_options = {:url => '/not-used', :html => {:class => user_form_class('form-horizontal'), :id =>  'update_login_and_password', :data => {token: session[:token]}}, :validate => true}
= simple_form_for @user, form_options do |f|
  %legend= t(:change_password)
  = hidden_field_tag 'user_param', @user.to_param
  .hidden
    = f.input :login, :label => t(:username), :required => false, :input_html => {:id => :srp_username}
  = f.input :password, :required => false, :validate => true, :input_html => { :id => :srp_password }
  = f.input :password_confirmation, :required => false, :input_html => { :id => :srp_password_confirmation }
  .form-group
    .controls
      = f.submit t(:save), :class => 'btn btn-primary'

app/views/users/_change_pgp_key.html.haml
-#
-# CHANGE PGP KEY
-#
-# this will be replaced by a identities controller/view at some point
-#

- form_options = {:html => {:class => user_form_class('form-horizontal'), :id => 'update_pgp_key', :data => {token: session[:token]}}, :validate => true}
= simple_form_for [:api, @user], form_options do |f|
  %legend= t(:advanced_options)
  = f.input :public_key, :as => :text, :hint => t(:use_ascii_key), :input_html => {:class => "full-width", :rows => 4}
  .form-group
    .controls
      = f.submit t(:save), :class => 'btn', :data => {"loading-text" => "Saving..."}

app/views/users/_change_service_level.html.haml
:ruby
  # DISABLED! this form points to a route that does not exist.
  #   It's a draft for implementing service levels.
  # TODO: probably won't want here, but here for now.
  #       We will need way to ensure payment for a non-free plan.
  #
  # SERVICE LEVEL
  #
  #
- if APP_CONFIG[:service_levels] && false
  - form_options = {:html => {:class => user_form_class('form-horizontal'), :id => 'update_service_level', :data => {token: session[:token]}}, :validate => true}
  = simple_form_for @user, form_options do |f|
    %legend= t(:service_level)
    - if @user != current_user
      = t(:desired_service_level)
    = f.select :desired_service_level_code, ServiceLevel.select_options, :selected => @user.desired_service_level.id
    - if @user != current_user
      %p
      = t(:effective_service_level)
      = f.select :effective_service_level_code, ServiceLevel.select_options, :selected => @user.effective_service_level.id
    .form-group
      .controls
        = f.submit t(:save), :class => 'btn', :data => {"loading-text" => "Saving..."}

app/views/users/_contact_email.html.haml
%legend= t(:contact_email)
= simple_form_for @user, {:validate => true} do |f|
  %p= t(:contact_email_info)
  = f.input :contact_email, :label => false
  -# %p= t(:public_key)
  -# = f.text_area :contact_email_key, {:class => "full-width", :rows => 4}
  .form-group
    .controls
      = f.submit t(:save), :class => 'btn', :data => {"loading-text" => "Saving..."}

app/views/users/_destroy_account.html.haml
-#
-# DESTROY ACCOUNT
-#

%legend
  - if @user == current_user
    = t(:destroy_my_account)
  - else
    = t(:admin_destroy_account, :username => @user.login)
%p= t(:destroy_account_info)
= destroy_btn user_path(@user), :type => "danger" do
  %i.icon-remove.icon-white
  = t(:destroy_my_account)
- if @user != current_user and @user.enabled?
  %legend
    = t(:deactivate_account, :username => @user.login)
  %p= t(:deactivate_description)
  = btn deactivate_user_path(@user), :method => :post, :type => "warning"  do
    %i.icon-pause.icon-white
    = t(:deactivate)
- elsif @user != current_user and !@user.enabled?
  %legend
    = t(:enable_account, :username => @user.login)
  %p= t(:enable_description)
  = btn enable_user_path(@user), :method => :post, :type => "warning"  do
    %i.icon-ok.icon-white
    = t(:enable)

app/views/users/_edit.html.haml
-#
-# edit user form, used by both show and edit actions.
-#
-# We render a bunch of forms here. Which we use depends upon config settings
-# user_actions and admin_actions. They both include an array of actions 
-# allowed to users and admins.
-# Possible forms are:
-#  'change_password'
-#  'change_pgp_key'
-#  'change_service_level'
-#  'destroy_account'
- actions = APP_CONFIG[admin? ? :admin_actions : :user_actions] || []
- actions.each do |action|
  = render action

app/views/users/_overview.html.haml
.overview

  %h2.first= t(".welcome", username: @user.login, cascade: true)

  - if admin?
    %p
      = t(:created)
      = @user.created_at
      %br
      = t(:updated)
      = @user.updated_at
      %br
      = t(:enabled)
      = @user.enabled?

  %p= t(:overview_intro, default: "")

  %ul.unstyled
    %li= icon('user') + link_to(t(".account"), edit_user_path(@user))
    - # %li= icon('envelope') + link_to(t(:overview_email), {insert path for user identities, presuambly}
    %li= icon('question-sign') + link_to(t(".tickets"), user_tickets_path(@user))
    %li= icon('shopping-cart') + link_to(t(".billing"), billing_top_link(@user)) if APP_CONFIG[:billing]

app/views/users/_user.html.haml
%tr
  %td
    = link_to user.username, user
  %td
    = simple_date(user.created_at)
  %td
    = simple_date(user.updated_at)
  %td
    - if user.enabled
      %button.btn.btn-sm.btn-default{:"data-toggle" => "modal", :"data-target" => "#user-form-#{user.id}", :type => "button"}
        = t("actions.disable_user")
      .modal.fade.hide{:id => "user-form-#{user.id}"}
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{:"data-dismiss" => "modal"} ×
              = t("actions.confirm_user_deactivation", username: user.username)
            .modal-footer
              = form_tag deactivate_user_path(user) do
                %input.btn.btn-default.btn-danger{:type => "submit", :value => "#{t("actions.disable_user")}"}
    - else
      %button.btn.btn-sm.btn-default{:"data-toggle" => "modal", :"data-target" => "#user-form-#{user.id}", :type => "button"}
        = t("actions.enable_user")
      .modal.fade.hide{:id => "user-form-#{user.id}"}
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{:"data-dismiss" => "modal"} ×
              = t("actions.confirm_user_activation", username: user.username)
            .modal-footer
              = form_tag enable_user_path(user) do
                %input.btn.btn-default.btn-danger{:type => "submit", :value => "#{t("actions.enable_user")}"}

app/views/users/edit.html.haml
= render 'edit'

app/views/users/index.html.haml
- @show_navigation = false

= search :users
= table @users, %w(username created updated actions)

app/views/users/show.html.haml
= render 'overview'
.container-fluid
  .row
    %h4 To use bitmask services:
    = btn client_download_url, type: "primary" do
      %i.icon-arrow-down.icon-white
      = t(:download_bitmask)