engines/billing/config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => CommonLanguages.match_available do

    get 'payments/new' => 'payments#new', :as => :new_payment
    post 'payments/confirm' => 'payments#confirm', :as => :confirm_payment
    #  match 'payments/new' => 'payments#new', :as => :new_payment
    #  match 'payments/confirm' => 'payments#confirm', :as => :confirm_payment
    #resources :users do
    # resources :payments, :only => [:new, :confirm]
    #  resources :subscriptions, :only => [:index, :destroy]
    #end
    resources :subscriptions, :only => [:index, :show] do
      member do
        post 'subscribe'
        delete 'unsubscribe'
      end
    end

    resources :customer, :only => [:new, :edit]

    get 'billing_admin' => 'billing_admin#show'
  end
end

engines/billing/app/controllers/payments_controller.rb
class PaymentsController < BillingBaseController
  before_filter :require_login, :only => [:index]

  respond_to :html

  def new
    if current_user.has_payment_info?
      @client_token = Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
    else
      @client_token = Braintree::ClientToken.generate
   end
  end

# not sure if this should be kept
  def index
    access_denied unless admin? or (@user == current_user)
    customer = Customer.find_by_user_id(@user.id)
    braintree_data = Braintree::Customer.find(customer.braintree_customer_id)
    # these will be ordered by created_at descending, per http://stackoverflow.com/questions/16425475/
    @transactions = braintree_data.transactions
  end

  def confirm
    make_transaction
    if @result.success?
      flash[:success] = I18n.t(:donation_sucess)
    else
      flash[:error] = I18n.t(:donation_not_sucess)
    end
    redirect_to action: :new, locale: params[:locale]
  end


  private
  def make_transaction
    if current_user.has_payment_info?
      transact_without_user_info
   elsif current_user.is_anonymous?
      transact_without_user_info
    else
      transact_with_user_info
    end
  end

  def transact_with_user_info
    @result = Braintree::Transaction.sale(
               amount: params[:amount],
               payment_method_nonce: params[:payment_method_nonce],
               customer: {
                  first_name: params[:first_name],
                  last_name: params[:last_name],
                  company: params[:company],
                  email: current_user.email,
                  phone: params[:phone]
                },
                options: {
                  store_in_vault: true
                })
    current_user.update_attributes(braintree_customer_id: @result.transaction.customer_details.id) if @result.success?
  end

  def transact_without_user_info
    @result = Braintree::Transaction.sale(
               amount: params[:amount],
               payment_method_nonce: params[:payment_method_nonce],
              )
  end
end

engines/billing/app/views/payments/_customer_form.html.haml
%p
  = t(:personal_info)
%div
  = text_field_tag :first_name, "",placeholder: "#{t(:first_name)}", class: "radius"
%div
  = text_field_tag :last_name, "",placeholder: "#{t(:last_name)}", class: "radius"
%div
  = text_field_tag :company, "",placeholder: "#{t(:company)}", class: "radius"
%div
  = text_field_tag :phone, "",placeholder: "#{t(:phone)}", class: "radius"

engines/billing/app/views/payments/index.html.haml
/ check if necessary
%h2=t :transaction_history
- if (@transactions.count == 0)
  = t(:no_transaction_history)
- @transactions.each do |t|
  = render :partial => "transaction_details", :locals => {:transaction => t}

engines/billing/app/views/payments/new.html.haml
%h2.mbs
  = t(:new_donation)
%br/
= form_tag confirm_payment_path, id: "checkout-form" do
  - if current_user and !current_user.has_payment_info?
    = render 'customer_form' unless current_user.is_anonymous?
  %p
    = t(:donation_info)
  %div{:id => "payment-form" }
  %div{:id => "coinbase-container-id" }
  %input{:name => "amount", :placeholder => "#{t(:donation_amount)}", :type => "text"}
    %input.btn.btn-primary{:type => "submit", :value => "#{t(:donate)}"}
%script{:src => "https://js.braintreegateway.com/v2/braintree.js"}
:javascript
  var clientToken = "#{@client_token}";
  braintree.setup(clientToken, "dropin", {
    container: "payment-form",
    form: "checkout-form",
    coinbase: { container: "coinbase-container-id" }
  });