config/routes.rb
LeapWeb::Application.routes.draw do
  #
  # Please do not use root_path or root_url. Use home_path and home_url instead,
  # so that the path will be correctly prefixed with the locale.
  #
  root :to => "home#index"
  get '(:locale)' => 'home#index', :locale => CommonLanguages.match_available, :as => 'home'

  #
  # HTTP Error Handling
  # instead of the default error pages use the errors controller and views
  #
  match '/404' => 'errors#not_found', via: [:get, :post]
  match '/500' => 'errors#server_error', via: [:get, :post]

  scope "(:locale)", :locale => CommonLanguages.match_available, :controller => 'pages', :action => 'show' do
    get 'privacy-policy', :as => 'privacy_policy'
    get 'terms-of-service', :as => 'terms_of_service'
    get 'about', :as => 'about'
    get 'contact', :as => 'contact'
    get 'pricing', :as => 'pricing'
    get 'bye', :as => 'bye'
  end

  get '/provider.json' => 'static_config#provider'

  namespace "api", { module: "api",
      path: "/:version/",
      defaults: {version: '2', format: 'json'},
      :constraints => { :id => /[^\/]+(?=\.json\z)|[^\/]+/, :version => /[12]/ }
      } do
    resources :sessions, :only => [:new, :create, :update]
    delete "logout" => "sessions#destroy", :as => "logout"
    resources :users, :only => [:create, :update, :destroy, :index, :show]
    resources :messages, :only => [:index, :update]
    resource :cert, :only => [:show, :create]
    resource :smtp_cert, :only => [:create]
    resource :service, :only => [:show]
    resources :configs, :only => [:index, :show]
    resources :identities, :only => [:show]
  end

  scope "(:locale)", :locale => CommonLanguages.match_available do
    get "login" => "sessions#new", :as => "login"
    delete "logout" => "sessions#destroy", :as => "logout"

    get "signup" => "account#new", :as => "signup"
    resources :users, :except => [:new, :create, :update] do
      # resource :email_settings, :only => [:edit, :update]
      # resources :email_aliases, :only => [:destroy], :id => /.*/
      post 'deactivate', on: :member
      post 'enable', on: :member
    end

    resources :invite_codes, :only => [:index, :destroy, :create]
    resources :identities, :only => [:index, :destroy]
  end

  get "/.well-known/host-meta" => 'webfinger#host_meta'
  get "/webfinger" => 'webfinger#search'
  get "/key/:login" => 'keys#show', :constraints => { :login => /[^\/]+/ }

end

app/views/common/_action.html.haml
%li.action{class: action.class}
  =link_to action.label, action.url, action.html_options

app/views/common/_action_buttons.html.haml
.home-buttons
  .row.second
    .login.col-md-4
      %span.link= btn icon('ok-sign') + t(:login), login_path
      %span.info= t(:login_info, default: "")
    - if APP_CONFIG[:allow_registration]
      .signup.col-md-4
        %span.link= btn icon('user') + t(:signup), signup_path
        %span.info= t(:signup_info, default: "")
    - else
      .signup.col-md-4
    .help.col-md-4
      %span.link= btn icon('question-sign') + t(:get_help), new_ticket_path
      %span.info= t(:support_info, default: "")

app/views/common/_download_button.html.haml
.home-buttons
  .row.first
    .col-md-2
    .download.col-md-8
      = btn client_download_url, type: [:large, :primary] do
        = big_icon('download')
        = t(:download_bitmask)
    .col-md-2

app/views/common/_home_page_buttons.html.haml
= render 'common/download_button'
- if local_assigns[:divider]
  .row
    .col-md-12
      = render local_assigns[:divider]
= render 'common/action_buttons'

app/views/common/_navigation_item.html.haml
-#
-# A very simple navigation link. It takes a symbol, uses it for the
-# translation, path and determining if the link is active.
-#
-# For something more complex use link_to_navigation directly instead.
-#
- item = navigation_item.to_s
= link_to_navigation ".#{item}", polymorphic_url(item),
  active: controller?(item)

app/views/common/_search.html.haml
= form_tag path, :method => :get, :class => "form-search" do
  .input-append
    = text_field_tag :query, params[:query],
      id: "#{id}-typeahead",
      class: "search-query",
      autocomplete: :off
    %button.btn{:type => :submit}= submit_label

app/views/common/_table.html.haml
-# 
-# A simple table with headers, content and a message if there is no
-# content.
-# You can use the table helper method to translate the headers and
-# error message.
-#
%table.table.table-striped.table-bordered
  %thead
    %tr
      - headers.each do |header|
        %th= header
  %tbody
    - if content.present?
      = render content.all
    - else
      %tr
        %td{:colspan=>headers.count}= none