config/routes.rb
LeapWeb::Application.routes.draw do
  #
  # Please do not use root_path or root_url. Use home_path and home_url instead,
  # so that the path will be correctly prefixed with the locale.
  #
  root :to => "home#index"
  get '(:locale)' => 'home#index', :locale => CommonLanguages.match_available, :as => 'home'

  #
  # HTTP Error Handling
  # instead of the default error pages use the errors controller and views
  #
  match '/404' => 'errors#not_found', via: [:get, :post]
  match '/500' => 'errors#server_error', via: [:get, :post]

  scope "(:locale)", :locale => CommonLanguages.match_available, :controller => 'pages', :action => 'show' do
    get 'privacy-policy', :as => 'privacy_policy'
    get 'terms-of-service', :as => 'terms_of_service'
    get 'about', :as => 'about'
    get 'contact', :as => 'contact'
    get 'pricing', :as => 'pricing'
    get 'bye', :as => 'bye'
  end

  get '/provider.json' => 'static_config#provider'

  namespace "api", { module: "api",
      path: "/:version/",
      defaults: {version: '2', format: 'json'},
      :constraints => { :id => /[^\/]+(?=\.json\z)|[^\/]+/, :version => /[12]/ }
      } do
    resources :sessions, :only => [:new, :create, :update]
    delete "logout" => "sessions#destroy", :as => "logout"
    resources :users, :only => [:create, :update, :destroy, :index, :show]
    resources :messages, :only => [:index, :update]
    resource :cert, :only => [:show, :create]
    resource :smtp_cert, :only => [:create]
    resource :service, :only => [:show]
    resources :configs, :only => [:index, :show]
    resources :identities, :only => [:show]
  end

  scope "(:locale)", :locale => CommonLanguages.match_available do
    get "login" => "sessions#new", :as => "login"
    delete "logout" => "sessions#destroy", :as => "logout"

    get "signup" => "account#new", :as => "signup"
    resources :users, :except => [:new, :create, :update] do
      # resource :email_settings, :only => [:edit, :update]
      # resources :email_aliases, :only => [:destroy], :id => /.*/
      post 'deactivate', on: :member
      post 'enable', on: :member
    end

    resources :invite_codes, :only => [:index, :destroy, :create]
    resources :identities, :only => [:index, :destroy]
  end

  get "/.well-known/host-meta" => 'webfinger#host_meta'
  get "/webfinger" => 'webfinger#search'
  get "/key/:login" => 'keys#show', :constraints => { :login => /[^\/]+/ }

end

app/views/layouts/_admin_navigation_item.html.haml
- item = admin_navigation_item.to_s
%li{:class => ("active" if controller?(item))}
  = link_to t(".#{item}", cascade: true), path_for(item)

app/views/layouts/_content.html.haml
-#
-# Partial for displaying the page content. This is the only place that content should be displayed (except for home layout)
-#

- if content_for?(:content)
  - content = yield(:content)
- else
  - content = yield

- if @show_navigation && @user
  .col-md-2
    = render 'layouts/navigation'
  .span10
    = render 'layouts/messages'
    = content
- else
  .span12
    = render 'layouts/messages'
    = content

app/views/layouts/_footer.html.haml
- if CommonLanguages.available.size > 1
  .locales.row
    .wrap-text
      = locales_links
- else
  .locales.row
.links.row
  .wrap-text
    = link_to icon('home') + t(:home), home_path
    = link_to icon('eye-close') + t(:privacy_policy), privacy_policy_path
    = link_to icon('file') + t(:terms_of_service), terms_of_service_path
    - if lookup_context.exists?('pages/about')
      = link_to icon('info-sign') + t(:about), about_path
    - if lookup_context.exists?('pages/contact')
      = link_to icon('comment') + t(:contact), contact_path
    - if paid_service_level?
      = link_to icon('shopping-cart') + t(:pricing), pricing_path
    = link_to icon('barcode') + t(:Donations), new_payment_path if APP_CONFIG[:payment].present?

app/views/layouts/_header.html.haml
- if admin?
  %ul.nav.nav-pills.admin-area
    = render partial: 'common/navigation_item',
      collection: [:users, :identities, :invite_codes, :tickets]
    = link_to_navigation :logout, logout_path, :method => :delete
- if @user && @show_navigation
  .lead
    = @user.email_address

app/views/layouts/_masthead.html.haml
#masthead
  .title
    %span.sitename
      %a{:href => home_path}= APP_CONFIG[:domain]

app/views/layouts/_messages.html.haml
#messages
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert alert-#{name == :notice ? "success" : name}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, format_flash(msg), :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.sidenav
  = link_to_navigation :overview, @user,
    active: (controller?(:users) && action?(:show))
  = link_to_navigation :account_settings, edit_user_path(@user),
    active: (controller?(:users) && !action?(:show))
  - # will want link for identity settings
  = link_to_navigation ".tickets", auto_tickets_path,
    active: controller?(:tickets)
  - if APP_CONFIG[:billing]
    = link_to_navigation :donations, new_payment_path,
      active: (controller?(:donations) and action?(:new))
    = link_to_navigation :subscriptions, billing_top_link(@braintree_customer_id),
      active: controller?(:subscriptions)
  - unless admin?
    = link_to_navigation :logout, logout_path, method: :delete

app/views/layouts/application.html.haml
- @show_navigation = true if @show_navigation.nil? && logged_in?
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= html_title
      %meta{:content => content_for?(:description) ? yield(:description) : "Leap Web", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    #wrap
      = render 'layouts/masthead'
      #main
        .container-fluid
          - if @show_navigation && !admin?
            .row
              %h1= t(:user_control_panel)
          - if logged_in?
            .row
              .col-md-12
                = render 'layouts/header'
          .row
            = render 'layouts/content'
      #push
        -# #push is used for sticky footer in bootstrap 2. remove when upgrading to bootstrap 3
    #footer
      = render 'layouts/footer'

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= html_title
      %meta{:content => content_for?(:description) ? yield(:description) : "LEAP Web", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body.home
    = yield